### basic settings

# site properties and page defaults
title: Nat Pombubpa Lab
description: Where Fungi Starts with Fun!!!
logo: images/logo.svg
logo-text: false
header: images/backgrounds/Cover.jpg
footer: images/backgrounds/Cover.jpg
baseurl: ""

# site social media and other links
links:
  email: natpombubpa@gmail.com
  google-scholar: Nuttapon Pombubpa
  github: natpombubpa-lab
  #twitter: GreeneScientist
  instagram: npombubpa

### advanced settings

# default front matter parameters for markdown files
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

# collections
collections:
  members:
    output: true

# sass settings
sass:
  sass_dir: css

# syntax highlighting
highlighter: rouge

# plugins
plugins:
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-sitemap
  # - jekyll-github-metadata
  # - jekyll-avatar
  # - jekyll-gist
  # - jekyll-mentions
  # - jekyll-relative-links
  # - jemoji

# jekyll theme
theme: null
