- id: doi:10.1128/mra.01080-23
  image: https://en.wikipedia.org/wiki/American_Society_for_Microbiology#/media/File:American_Society_for_Microbiology_logo.png
  extra-links:
    - type: journal
  tags:
    - Metatranscriptomes
    - Biocrust
    - Desert microbes

- id: doi:10.3390/life14010011
  image: https://www.mdpi.com/life/life-14-00011/article_deploy/html/images/life-14-00011-g004.png
  extra-links:
    - type: journal
  tags:
    - Streptomyces
    - Microbial biogeography
    - Biodiversity

- id: doi:10.3389/fmicb.2023.1135800
  image: https://www.frontiersin.org/files/Articles/1135800/fmicb-14-1135800-HTML/image_m/fmicb-14-1135800-g001.jpg
  extra-links:
    - type: journal
  tags:
    - Chihuahuan Desert
    - Surface soil microbiomes
    - Amplicon sequencing
    
- id: doi:10.1007/s11104-023-05896-w
  image: https://github.com/natpombubpa-lab/natpombubpa-lab.github.io/assets/54328862/c43c831f-26a9-43b3-9cf1-3092166abbe2
  extra-links:
    - type: journal
  tags:
    - Legacy effects
    - Soil fungal communities
    - Plant-soil feedbacks

- id: doi:10.1016/j.jbiotec.2022.11.008
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0168165622002711-ga1_lrg.jpg
  extra-links:
    - type: journal
  tags:
    - Mixed Microalgal and Bacterial (MMB)
    - nitrogen and phosphorus recoveries

- id: doi:10.3389/fmicb.2022.856454
  image: https://www.frontiersin.org/files/Articles/856454/fmicb-13-856454-HTML/image_m/fmicb-13-856454-g001.jpg
  extra-links:
    - type: journal
  tags:
    - Dust Microbiome
    - Amplicon sequencing
    - Fungi
    - Sierra Nevada

- id: doi:10.1128/MRA.00494-21
  image: https://user-images.githubusercontent.com/54328862/123938574-6ddc4600-d9c1-11eb-876f-8a2a3441f955.png
  extra-links:
    - type: journal
  tags:
    - Rock-Inhabiting Microbes
    - Amplicon sequencing
    - Fungi
    - Joshua Tree National Park


- id: doi:10.1111/gcb.15340
  image: https://user-images.githubusercontent.com/54328862/118241983-ff9dfb80-b4c6-11eb-97ed-6e539f580564.jpg
  extra-links:
    - type: journal
  tags:
    - Alpine woody encroachment
    - Plant traits
    - Amplicon sequencing
    - Fungi

- id: doi:10.1093/femsec/fiaa125
  image: https://user-images.githubusercontent.com/54328862/94088799-3901e980-fdc6-11ea-9598-8d23b300f725.png
  extra-links:
    - type: journal
  tags:
    - Biocrust
    - Fungi-bacteria networks
    - Desert microbes
    - Amplicon sequencing
    - Fungi

- id: doi:10.3390/microorganisms8060942
  image: https://www.mdpi.com/microorganisms/microorganisms-08-00942/article_deploy/html/images/microorganisms-08-00942-g001.png
  extra-links:
    - type: journal
  tags:
    - Antarctica
    - Endolithic communities
    - Fungi
    - Amplicon sequencing

- id: doi:10.1007/s00300-020-02625-2
  image: https://www.biorxiv.org/content/biorxiv/early/2019/06/21/676775/F1.large.jpg
  extra-links:
    - type: journal
  tags:
    - Antarctica
    - Endolithic communities
    - Amplicon sequencing

- id: doi:10.3390/life10020013
  image: https://www.mdpi.com/life/life-10-00013/article_deploy/html/images/life-10-00013-g001.png
  extra-links:
    - type: journal
  tags:
    - Antarctica
    - Endolithic communities
    - Amplicon sequencing
    - McMurdo Dry Valleys
    - Fungi

- id: doi:10.1111/1758-2229.12788
  image: https://sfamjournals.onlinelibrary.wiley.com/cms/asset/1933421f-babc-4b27-973d-309c2d817d6a/emi4.v11.5.cover.jpg
  extra-links:
    - type: journal
  tags:
    - Antarctica
    - Endolithic communities
    - Amplicon sequencing
    - McMurdo Dry Valleys
    - Bacteria

- id: doi:10.3389/fevo.2019.00344
  image: https://frontiersinblog.files.wordpress.com/2016/09/ecology_290x290.png
  extra-links:
    - type: journal
  tags:
    - Biocrust
    - Fungi
    - Bacteria
    - Dispersal
    - Reproduction


- id: doi:10.3389/fmicb.2018.01392
  image: https://www.frontiersin.org/files/Articles/364185/fmicb-09-01392-HTML/image_m/fmicb-09-01392-g002.jpg
  extra-links:
    - type: journal
  tags:
    - Antarctica
    - Endolithic communities
    - Amplicon sequencing
    - Extremophiles
    - Fungi

- id: doi:10.3390/life8020019
  image: https://www.mdpi.com/life/life-08-00019/article_deploy/html/images/life-08-00019-g001.png
  extra-links:
    - type: journal
  tags:
    - Antarctica
    - Endolithic communities
    - Amplicon sequencing
    - FUNGuild
    - Fungi

- id: doi:10.1111/mec.14694
  image: https://onlinelibrary.wiley.com/cms/asset/a25c0500-6c32-466b-9f13-73b4e2c0896c/mec14694-fig-0004-m.png
  extra-links:
    - type: journal
  tags:
    - Shrub range expansion
    - Soil fungal communities
    - Amplicon sequencing
    - Fungi


- id: doi:10.3897/mycokeys.16.10000
  image: https://bdj.pensoft.net/showimg.php?filename=big_104190.jpg
  extra-links:
    - type: journal
  tags:
    - Built environment
    - Indoor fungi
    - ITS
    - Annotation
    - Mycobiome
